apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379             # port change to 6379 from 6380
      targetPort: 6379        # port change to 6379 from 6380
      protocol: TCP
  selector:
    app: redis
